# This is a basic workflow to help you get started with Actions

name: doc-generator

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install plantuml
        run: |
          sudo apt-get update -y
          sudo apt-get install -y plantuml
        
      - uses: actions/setup-ruby@v1.0.0
      
      - uses: actions/checkout@v2
    
      - name: setup bundler and install dependencies
        run: |
          gem install bundler:1.17.3
          cd docs_md
          bundle install
    
      - name: generate documentation
        run: echo $PWD

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Runs a single command using the runners shell
    #- name: Run a one-line script
     # run: echo Hello, world!

    # Runs a set of commands using the runners shell
#    - name: Run a multi-line script
 #     run: |
  #      echo Add other actions to build,
   #     echo test, and deploy your project.
